theme: bordeaux-program-theme
_merge: deep
params:
  plausible: mp.iut.u-bordeaux.fr
  debug:
    productionUrl: https://mp.iut.u-bordeaux.fr
  logo:
    header: "/assets/images/logo-mp.svg"
    footer: "/assets/images/logo-mp-footer.svg"